# Generated by Django 3.1.7 on 2021-06-06 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('duty', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_rookie', models.BooleanField(default=True)),
                ('is_open_staff', models.BooleanField(default=False)),
                ('is_pre_close_staff', models.BooleanField(default=False)),
                ('is_close_staff', models.BooleanField(default=False)),
                ('start_default', models.TimeField(default=datetime.time(8, 0))),
                ('end_default', models.TimeField(default=datetime.time(17, 0))),
                ('desired_times_per_week', models.IntegerField(blank=True, default=0, null=True)),
                ('desired_working_time', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
