# Generated by Django 3.1.7 on 2021-06-06 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShitItem',
            fields=[
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('is_work', models.BooleanField(default=False)),
                ('is_all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shift')),
            ],
        ),
    ]
