# Generated by Django 3.1.7 on 2021-06-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shift_shititem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShitItem',
            new_name='ShiftItem',
        ),
    ]
