# Generated by Django 3.1.7 on 2021-06-06 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210607_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shiftitem',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(3, 0)),
        ),
        migrations.AlterField(
            model_name='shiftitem',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0)),
        ),
    ]
