# Generated by Django 3.1.7 on 2021-06-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210628_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='shiftitem',
            name='is_all_day',
        ),
    ]
