# Generated by Django 3.1.7 on 2021-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210629_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftitem',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
