# Generated by Django 3.1.7 on 2021-09-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210919_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='user_name',
        ),
    ]
