# Generated by Django 3.1.7 on 2021-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_shift_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
